### ISSUE TITLE
Add visual to illustrate the threat model

### ISSUE THREAD

**Issue by robvanderveer** [OWASP/www-project-ai-security-and-privacy-guide#1]
A visual of the ai lifecycle with the discussed threads may be helpful in the document.

**Comment by Yvg2244** [comment]
can I do it

**Comment by Yvg2244** [comment]
Honestly speaking as a user it looks quiet messy and it has quality issue
it breaks on zooming.

**Comment by robvanderveer** [comment]
Interesting. Do you have ideas on how to improve it?
And can you elaborate about how it breaks on zooming? When I zoom in on Chrome, Firefox en Safari, it looks good.

**Comment by Yvg2244** [comment]
A better way could using illustration images for eg how architectures are show on GeeksForGeeks. They use 2-3 color scheme I am using brave and if I further zoom Experimentation/analysis part it will get blur and yellow background and white color do not go as good as black-white or blue white(to improve this use colors which have contrast ratio of more than 3.5 or 4) so that part not as eye catching as Dataprep or application code Sent from Mail for Windows From: Rob van der VeerSent: 10 March 2023 04:31To: OWASP/www-project-ai-security-and-privacy-guideCc: Yash Verdhan Gupta; CommentSubject: Re: [OWASP/www-project-ai-security-and-privacy-guide] Add visual to illustrate the threat model (Issue #1) Interesting. Do you have ideas on how to improve it?And can you elaborate about how it breaks on zooming? When I zoom in on Chrome, Firefox en Safari, it looks good.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by robvanderveer** [comment]
This sounds interesting. Can you provide a link to what you mean on Geeksforgeeks? Could I send you the powerpoint source of the diagram so you can give it a go?
