### ISSUE TITLE
MLOps

### ISSUE THREAD

**Issue by l3ra** [OWASP/www-project-ai-security-and-privacy-guide#8]
This could be more closely aligned to the MLOps pipeline - ie, feature engineering, model evaluation prior to deployment - particularly the diagram.

**Comment by robvanderveer** [comment]
I appreciate that the MLOps pipeline has detail beyond the diagram in the guide, and wrote a lot about it myself in the ISO/IEC 5338 standard. 
However, in  light of the security threats, these process details (e.g. feature engineering, labeling etc.) do not make a difference regarding the security threas discussed. This is why I use more abstract process descriptions.
When it comes to model evaluation however, I do see an opportunity to highlight that, because it has a speficif role as countermeasure.
Does this make sense to you as a response?

**Comment by l3ra** [comment]
Okay, I'd quite like to create a PR on using model evaluation as a countermeasure if that's an open topic

**Comment by robvanderveer** [comment]
Yes please! Let me know if you have any technical difficulties.
